name: bike_brands_app
description: A Flutter application showcasing different motorcycle brands

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/suzuki1.jpg
    - assets/images/suzuki2.jpg
    - assets/images/scrambler1.jpg
    - assets/images/scrambler2.jpg
    - assets/images/supersoco1.jpg
    - assets/images/supersoco2.jpg
    - assets/images/segway1.jpg
    - assets/images/segway2.jpg
    - assets/images/sondors1.jpg
    - assets/images/sondors2.jpg
    - assets/images/stark1.jpg
    - assets/images/stark2.jpg
    - assets/images/sur-ron1.jpg
    - assets/images/sur-ron2.jpg
    - assets/images/silence1.jpg
    - assets/images/silence2.jpg
    - assets/images/super73-1.jpg
    - assets/images/super73-2.jpg
    - assets/images/soriano1.jpg
    - assets/images/soriano2.jpg